[package]
name = "shrimple"
version = "0.1.0"
edition = "2021"
description = "Minimal CLI for static site generation, supercharged with Lua"
authors = ["Tim Kurdov <tim.kurdov@gmail.com>"]
repository = "https://github.com/schvv31n/shrimple"
license = "MIT"
keywords = ["template-engine"]
categories = ["template-engine", "compilers", "command-line-interface", "web-programming"]

[dependencies]
nom = "7"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
mlua = { version = "0.9", features = ["lua54"] }
ureq = "2.9.6"
shrimple-localhost = "3"

[lints.clippy]
unit_arg = "allow"
single_char_lifetime_names = "warn"
deref_by_slicing = "warn"
derive_partial_eq_without_eq = "warn"
expect_used = "warn"
unwrap_used = "warn"
explicit_iter_loop = "warn"
explicit_into_iter_loop = "warn"
